services:
  minio:
    image: docker.io/minio/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - minionetwork
    volumes:
       - type: bind
         source: /home/jry/data/baraky/data
         target: /data

    environment:
      - MINIO_ROOT_USER=${MINIO_username}
      - MINIO_ROOT_PASSWORD=${MINIO_password}
      #      - MINIO_DEFAULT_BUCKETS=estates
    command: server /data --console-address ":9001"
networks:
  minionetwork:
    driver: bridge
