services:
  notifier:
    build:
      context: .
      dockerfile: Dockerfile
      #    volumes:
      # - .:/app
    network_mode: "host"
    environment:
      - APP_ENV=development
      - APP_DEBUG=true    
    command: ["python", "main.py", "notifier"]

  watcher_flats:
    build:
      context: .
      dockerfile: Dockerfile
      #    volumes:
      # - .:/app
    network_mode: "host"
    environment:
      - APP_ENV=development
      - APP_DEBUG=true    
    command: ["python", "main.py", "watcher", "--query-path", "query_params_flats.json"]

  watcher_houses:
    build:
      context: .
      dockerfile: Dockerfile
      #    volumes:
      # - .:/app
    network_mode: "host"
    environment:
      - APP_ENV=development
      - APP_DEBUG=true    
    command: ["python", "main.py", "watcher", "--query-path", "query_params.json"]

  minio:
    image: docker.io/minio/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - minionetwork
    volumes:
       - type: bind
         source: /home/jry/data/baraky/data
         target: /data

    environment:
      - MINIO_ROOT_USER=${MINIO_username}
      - MINIO_ROOT_PASSWORD=${MINIO_password}
      #      - MINIO_DEFAULT_BUCKETS=estates
    command: server /data --console-address ":9001"
networks:
  minionetwork:
    driver: bridge
